spring:
  application:
    name: discovery-server
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



logging:
  level:
    com.netflix.eureka: 'OFF'
    org.springframework.cloud.netflix.eureka.server: 'DEBUG'