# Configuration file for appointment-service
server:
  port: 8200
spring:
  application:
    name: appointment-service
  datasource:
    username: root
    password: Ashish123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/appointment
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



